- name: List Lambda functions
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/config.yml
    - vars/secrets.yml
  tasks:
    - name: Fetch Lambda list
      amazon.aws.lambda_info:
        region: ap-southeast-2
      register: lambda_info

    - name: Show function names
      debug:
        msg: "{{ item.function_name }}"
      loop: "{{ lambda_info.functions }}"
