- name: Load vars from file
  hosts: web
  gather_facts: true
  vars_files:
    - vars/config.yml
  roles:
    - hello
  tasks:
    - name: Include database role
      include_role:
        name: hello2
      vars:
        app_path: mydb