name: Ansible Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3

      - name: Run Ansible playbook
        run: |
          ansible-playbook lambda_list.yml
        env:
          AWS_PROFILE: ${{ secrets.AWS_PROFILE }}

